services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: mariadb.dockerfile
    image: mariadb
    container_name: mariadb_1
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
  
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: wordpress.dockerfile
    image: wordpress
    container_name: wordpress_1
    restart: on-failure
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - db_password

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: nginx.dockerfile
    image: nginx
    container_name: nginx_1
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    restart: on-failure


secrets:
  db_password:
    file: ./secrets/db_password.txt

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver_opts:
      type: none
      device: /home/mgamraou/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mgamraou/data/wordpress
